syntax = "proto3";

package chat;

option go_package = "github.com/tomba07/bombshell/proto/chat";

service ChatService {
  rpc Join(JoinRequest) returns (JoinResponse);
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
  rpc Leave(LeaveRequest) returns (LeaveResponse);

  rpc Subscribe(SubscribeRequest) returns (stream Event);
}

message Event {
  EventType type = 1;
  string player_id = 2;
  string message = 3;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_CHAT = 1;
}

message JoinRequest {
  string name = 1;
}

message JoinResponse {
  string player_id = 1;
}

message SendMessageRequest {
  string player_id = 1;
  string message = 2;
}

message SendMessageResponse {
  bool ok = 1;
}

message LeaveRequest {
  string player_id = 1;
}

message LeaveResponse {
  bool ok = 1;
}

message SubscribeRequest {
  string player_id = 1;
}
